"""add_created_by_field

Revision ID: 1bff9f07d0bb
Revises: 7966d2b8f1b6
Create Date: 2026-06-10 20:53:17.142834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1bff9f07d0bb"
down_revision: Union[str, Sequence[str], None] = "7966d2b8f1b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "diet",
        sa.Column(
            "created_by",
            sa.Uuid(),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None,
        "diet",
        "user",
        ["created_by"],
        ["id"],
    )
    op.add_column(
        "diet_ingredient",
        sa.Column(
            "created_by",
            sa.Uuid(),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None,
        "diet_ingredient",
        "user",
        ["created_by"],
        ["id"],
    )
    op.add_column(
        "ingredient_self_reference",
        sa.Column(
            "created_by",
            sa.Uuid(),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None,
        "ingredient_self_reference",
        "user",
        ["created_by"],
        ["id"],
    )
    op.add_column(
        "meal",
        sa.Column(
            "created_by",
            sa.Uuid(),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None,
        "meal",
        "user",
        ["created_by"],
        ["id"],
    )
    op.add_column(
        "meal_dish",
        sa.Column(
            "created_by",
            sa.Uuid(),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None,
        "meal_dish",
        "user",
        ["created_by"],
        ["id"],
    )
    op.add_column(
        "recipe",
        sa.Column(
            "created_by",
            sa.Uuid(),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None,
        "recipe",
        "user",
        ["created_by"],
        ["id"],
    )
    op.add_column(
        "recipe_ingredient",
        sa.Column(
            "created_by",
            sa.Uuid(),
            nullable=False,
        ),
    )
    op.create_foreign_key(
        None,
        "recipe_ingredient",
        "user",
        ["created_by"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "recipe_ingredient", type_="foreignkey")
    op.drop_column("recipe_ingredient", "created_by")
    op.drop_constraint(None, "recipe", type_="foreignkey")
    op.drop_column("recipe", "created_by")
    op.drop_constraint(None, "meal_dish", type_="foreignkey")
    op.drop_column("meal_dish", "created_by")
    op.drop_constraint(None, "meal", type_="foreignkey")
    op.drop_column("meal", "created_by")
    op.drop_constraint(None, "ingredient_self_reference", type_="foreignkey")
    op.drop_column("ingredient_self_reference", "created_by")
    op.drop_constraint(None, "diet_ingredient", type_="foreignkey")
    op.drop_column("diet_ingredient", "created_by")
    op.drop_constraint(None, "diet", type_="foreignkey")
    op.drop_column("diet", "created_by")
    # ### end Alembic commands ###
