"""Ingrediend selfreference update

Revision ID: 476b8c291c34
Revises: 0ca0d728f8bf
Create Date: 2026-06-08 20:10:42.991798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "476b8c291c34"
down_revision: Union[str, Sequence[str], None] = "0ca0d728f8bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingredient_self_reference",
        sa.Column("is_alternative", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "ingredient_self_reference",
        sa.Column("include_in_count", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingredient_self_reference", "include_in_count")
    op.drop_column("ingredient_self_reference", "is_alternative")
    # ### end Alembic commands ###
