"""Add name to recipe

Revision ID: 7966d2b8f1b6
Revises: 90a9af03d66f
Create Date: 2026-06-10 20:34:08.921499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7966d2b8f1b6"
down_revision: Union[str, Sequence[str], None] = "90a9af03d66f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipe", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipe", "name")
    # ### end Alembic commands ###
